CREATE TABLE IF NOT EXISTS coupon (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY, 
  code VARCHAR(50) NOT NULL,
  discount INTEGER NOT NULL,
  valid TIMESTAMP NOT NULL,
  event_id UUID,
  FOREIGN KEY (event_id) REFERENCES event(id) ON DELETE CASCADE
);
